server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost       # MongoDB 主机地址
      port: 27017          # MongoDB 端口
      database: postcenter  # 数据库名称
  # 应用名称
  application:
    name: post-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9088

obs:
  endPoint: obs.cn-east-3.myhuaweicloud.com
  ak: TUDUSE2FLAMFLDFRICGU
  sk: C6edfKMnvlJFZTuG4r63GXmSh8EB75aS2EbJKRkT
  bucketName: jiffies
  prefix: https://jiffies.obs.cn-east-3.myhuaweicloud.com/